# Generated by Django 4.2 on 2025-05-08 13:53

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=recipes.models.Recipe.upload_to, verbose_name='картинка'),
        ),
    ]
